[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@OpenZeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/=lib/chainlink/",
]

[invariant]
runs = 128
depth = 128
fail_on_revert = true
